/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/actividades` | `/actividades`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/checkout` | `/tickets/checkout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/form` | `/tickets/form`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/paymentMethod` | `/tickets/paymentMethod`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/paymentResult` | `/tickets/paymentResult`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/ticketDetail` | `/tickets/ticketDetail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/ticketsHistory` | `/tickets/ticketsHistory`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/actividades` | `/actividades`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets/checkout` | `/tickets/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets/form` | `/tickets/form`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets/paymentMethod` | `/tickets/paymentMethod`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets/paymentResult` | `/tickets/paymentResult`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets/ticketDetail` | `/tickets/ticketDetail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets/ticketsHistory` | `/tickets/ticketsHistory`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/actividades${`?${string}` | `#${string}` | ''}` | `/actividades${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets/checkout${`?${string}` | `#${string}` | ''}` | `/tickets/checkout${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets/form${`?${string}` | `#${string}` | ''}` | `/tickets/form${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets${`?${string}` | `#${string}` | ''}` | `/tickets${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets/paymentMethod${`?${string}` | `#${string}` | ''}` | `/tickets/paymentMethod${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets/paymentResult${`?${string}` | `#${string}` | ''}` | `/tickets/paymentResult${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets/ticketDetail${`?${string}` | `#${string}` | ''}` | `/tickets/ticketDetail${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets/ticketsHistory${`?${string}` | `#${string}` | ''}` | `/tickets/ticketsHistory${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/actividades` | `/actividades`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/checkout` | `/tickets/checkout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/form` | `/tickets/form`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/paymentMethod` | `/tickets/paymentMethod`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/paymentResult` | `/tickets/paymentResult`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/ticketDetail` | `/tickets/ticketDetail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/ticketsHistory` | `/tickets/ticketsHistory`; params?: Router.UnknownInputParams; };
    }
  }
}
